Restore Open Sans as the default font
opentok/opentok-rtc pull request #674
Opened 2020-10-22 04:35 UTC by jeffswartz

2020-10-22 15:24 UTC, emilianop11 commented on README.md
>  * `USE_GOOGLE_FONTS` (Optional, default value: true): Whether the client app will load
Please be aware that the USE_GOOGLE_FONTS property is listed twice in the readme. One should go away :)

2020-10-22 15:27 UTC, emilianop11 requested changes

2020-10-22 15:27 UTC, emilianop11 commented on README.md
>  * `USE_GOOGLE_FONTS` (Optional, default value: true): Whether the client app will load
Also, this env tracks down to the `useGoogleFonts` variable, which i see being referenced but not used. Am i missing something?

2020-10-22 16:25 UTC, Raulkg commented on web/css/fonts.css
>    font-display: swap;
Preload this font in HTML. using the below line which makes the application faster.

`<link rel="preload" as="font" href="/fonts/custom-font.woff2" type="font/woff2" crossorigin="anonymous">`

2020-10-27 18:34 UTC, Raulkg approved these changes
LGTM

2020-10-27 20:13 UTC, emilianop11 approved these changes

2020-10-27 22:15 UTC, merged