[ECO-5813] Switch microphone is broken in room view
opentok/opentok-rtc pull request #692
Opened 2020-10-30 22:38 UTC by emilianop11

2020-10-30 22:57 UTC, Raulkg reviewed
I am getting console.logs on the browser as below:

requests.js:36 GET http://localhost:8123/room/old-feather-shiny-block-9866/rawInfo 404 (Not Found)
(anonymous) @ requests.js:36
sendXHR @ requests.js:8
getRoomRawInfo @ requests.js:56
(anonymous) @ precallController.js:106

2020-11-02 13:17 UTC, emilianop11 commented
> I am getting console.logs on the browser as below:
> 
> requests.js:36 GET http://localhost:8123/room/old-feather-shiny-block-9866/rawInfo 404 (Not Found)
> (anonymous) @ requests.js:36
> sendXHR @ requests.js:8
> getRoomRawInfo @ requests.js:56
> (anonymous) @ precallController.js:106

That is expected. It just means that the room you are trying to join does not exist yet.

2020-11-02 16:13 UTC, Raulkg commented
> > I am getting console.logs on the browser as below:
> > requests.js:36 GET http://localhost:8123/room/old-feather-shiny-block-9866/rawInfo 404 (Not Found)
> > (anonymous) @ requests.js:36
> > sendXHR @ requests.js:8
> > getRoomRawInfo @ requests.js:56
> > (anonymous) @ precallController.js:106
> 
> That is expected. It just means that the room you are trying to join does not exist yet.

i don't think we should throw an error in console logs. we should handle errors like this using try catch

2020-11-02 18:04 UTC, Raulkg commented on web/js/precallController.js
> +              roomURI: roomName,
roomName variable is also declared in upper scope. Consider changing the variable name to avoid confusion.

2020-11-02 19:27 UTC, Raulkg approved these changes
I will address the issue of critical js with a different patch PR.

for now this LGTM

2020-11-02 20:08 UTC, jeffswartz requested changes

2020-11-02 20:14 UTC, jeffswartz requested changes
There's a reference to views/index.ejs in Gruntfile.js. And in CUSTOMIZING-UI.md.

2020-11-02 21:07 UTC, jeffswartz approved these changes

2020-11-02 21:42 UTC, merged